import type { IREnum, IRField, IRMessage, IRReserved, IRService, IRType } from "@zodem/core";
import { upperSnake } from "@zodem/core";

export interface EmitFileInput {
  package: string;
  messages: IRMessage[];
  services: IRService[];
  imports: Iterable<string>;
}

function shortName(fullName: string): string {
  return fullName.split(".").pop() as string;
}

function relativeName(fullName: string, packageName: string): string {
  return fullName.startsWith(`${packageName}.`) ? fullName.slice(packageName.length + 1) : fullName;
}

function typeNameFor(type: IRType, packageName: string): string {
  switch (type.kind) {
    case "scalar":
      return type.name;
    case "message":
    case "enum":
      return relativeName(type.fullName, packageName);
    case "wkt":
      return type.fullName;
    case "map":
      return `map<${type.key}, ${typeNameFor(type.value, packageName)}>`;
  }
}

function emitReserved(reserved: IRReserved[], indent: string): string[] {
  if (reserved.length === 0) return [];
  const numbers = [...reserved].map((r) => r.number).sort((a, b) => a - b);
  const names = [...reserved].map((r) => r.name).sort();
  const lines: string[] = [];
  if (numbers.length > 0) lines.push(`${indent}reserved ${numbers.join(", ")};`);
  if (names.length > 0) lines.push(`${indent}reserved ${names.map((n) => JSON.stringify(n)).join(", ")};`);
  return lines;
}

function emitFieldLine(field: IRField, packageName: string, indent: string): string {
  const label = field.oneof ? "" : field.label === "repeated" ? "repeated " : field.label === "optional" ? "optional " : "";
  const typeName = typeNameFor(field.type, packageName);
  return `${indent}${label}${typeName} ${field.name} = ${field.number};`;
}

function emitMessage(msg: IRMessage, packageName: string, indentLevel: number): string[] {
  const indent = "  ".repeat(indentLevel);
  const inner = "  ".repeat(indentLevel + 1);
  const lines: string[] = [`${indent}message ${shortName(msg.fullName)} {`];

  lines.push(...emitReserved(msg.reserved, inner));

  const regularFields = msg.fields
    .filter((f) => !f.oneof)
    .sort((a, b) => (a.number ?? 0) - (b.number ?? 0));
  for (const field of regularFields) {
    lines.push(emitFieldLine(field, packageName, inner));
  }

  const oneofNames = [...new Set(msg.fields.filter((f) => f.oneof).map((f) => f.oneof as string))].sort();
  for (const oneofName of oneofNames) {
    lines.push(`${inner}oneof ${oneofName} {`);
    const members = msg.fields
      .filter((f) => f.oneof === oneofName)
      .sort((a, b) => (a.number ?? 0) - (b.number ?? 0));
    for (const field of members) {
      lines.push(emitFieldLine(field, packageName, `${inner}  `));
    }
    lines.push(`${inner}}`);
  }

  const nestedMessages = [...msg.nested.messages].sort((a, b) => a.fullName.localeCompare(b.fullName));
  for (const nested of nestedMessages) {
    lines.push(...emitMessage(nested, packageName, indentLevel + 1));
  }
  const nestedEnums = [...msg.nested.enums].sort((a, b) => a.fullName.localeCompare(b.fullName));
  for (const en of nestedEnums) {
    lines.push(...emitEnum(en, indentLevel + 1));
  }

  lines.push(`${indent}}`);
  return lines;
}

function emitEnum(en: IREnum, indentLevel: number): string[] {
  const indent = "  ".repeat(indentLevel);
  const inner = "  ".repeat(indentLevel + 1);
  const shortNameVal = shortName(en.fullName);
  const zeroName = `${upperSnake(shortNameVal)}_UNSPECIFIED`;
  const lines: string[] = [`${indent}enum ${shortNameVal} {`];

  lines.push(...emitReserved(en.reserved, inner));
  lines.push(`${inner}${zeroName} = 0;`);
  const sortedValues = [...en.values].sort((a, b) => (a.number ?? 0) - (b.number ?? 0));
  for (const v of sortedValues) {
    lines.push(`${inner}${v.name} = ${v.number};`);
  }

  lines.push(`${indent}}`);
  return lines;
}

function emitService(svc: IRService, packageName: string): string[] {
  const lines: string[] = [`service ${shortName(svc.fullName)} {`];
  for (const m of svc.methods) {
    const reqType = relativeName(m.input, packageName);
    const resType = relativeName(m.output, packageName);
    const cs = m.clientStreaming ? "stream " : "";
    const ss = m.serverStreaming ? "stream " : "";
    lines.push(`  rpc ${m.name}(${cs}${reqType}) returns (${ss}${resType}) {}`);
  }
  lines.push(`}`);
  return lines;
}

export function emitProto(input: EmitFileInput): string {
  const lines: string[] = [`// Code generated by zodem. DO NOT EDIT.`, `syntax = "proto3";`, "", `package ${input.package};`];

  const imports = [...new Set(input.imports)].sort();
  if (imports.length > 0) {
    lines.push("");
    for (const imp of imports) lines.push(`import "${imp}";`);
  }

  const messages = [...input.messages].sort((a, b) => a.fullName.localeCompare(b.fullName));
  for (const msg of messages) {
    lines.push("");
    lines.push(...emitMessage(msg, input.package, 0));
  }

  const services = [...input.services].sort((a, b) => a.fullName.localeCompare(b.fullName));
  for (const svc of services) {
    lines.push("");
    lines.push(...emitService(svc, input.package));
  }

  lines.push("");
  return lines.join("\n");
}

const VERSION_SEGMENT = /^v\d+(alpha\d*|beta\d*)?$/;

/** "acme.user.v1" -> "acme/user/v1/user.proto" */
export function outputPathFor(packageName: string): string {
  const segments = packageName.split(".");
  const last = segments[segments.length - 1] ?? "";
  const isVersion = VERSION_SEGMENT.test(last) && segments.length > 1;
  const fileBase = isVersion ? segments[segments.length - 2] : last;
  return `${segments.join("/")}/${fileBase}.proto`;
}
